// a router to populate the database with seed data
const router = require('express').Router()
const { DRIVERS, CUSTOMERS, RIDES } = require('../data/seed')
const db = require('../models')

// endpoint to do the seeding
router.post('/', async (req, res) => {
    // create a transaction object to hold the different seeding steps
    const t = await db.sequelize.transaction()

    // TODO: Prevent duplicates being added.

    try {
        // bulk create records
        await db.Customer.bulkCreate(CUSTOMERS, { transaction: t })
        await db.Driver.bulkCreate(DRIVERS, { transaction: t })
        await db.Ride.bulkCreate(RIDES, { transaction: t })

        // commit the transaction
        await t.commit()

        res.status(201).json({ status: 'success', message: 'Database successfully populated :)' })
    } catch (err) {
        console.log(err.message)

        // rollback a failed transaction
        await t.rollback()

        res.status(500).json({ status: "error", message: "Something went wrong seeding the database" })
        return
    }
})

module.exports = router


/*
Generate seed data for three related tables in my SQL database:
Driver: { fullname: String, licenseCode: ENUM('B', 'BA', 'C', 'D', 'E') }
Customer: { fullname: String }
Ride: {driverId: Int, customerId: Int, city: String, startTime: Date, endTime: Date, distance: Decimal, price: Decimal, rideState: ENUM('IN_PROGRESS', 'CANCELED', 'COMPLETED') }
Note: All primary key IDs are generated by the database engine.
I need 50 records for the Ride table, 10 for the Driver table, and 40 for the Customer table.
I need the data as 3 JavaScript arrays, i.e.:
const DRIVERS = [...]
const CUSTOMERS = [...]
const RIDES = [...]
Ask any clarifying questions if necessary.
*/